apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    matchLabels:
      app: fleetman-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
      - name: pos-apigateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  type: ClusterIP
  selector:
    app: fleetman-api-gateway
  ports:
  - name: http
    port: 8080
