apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-webapp
spec:
  selector:
    matchLabels:
      app: pos-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: pos-webapp
    spec:
      containers:
      - name: pos-webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: pos-webapp
spec:
  type: LoadBalancer
  selector:
    app: pos-webapp
  ports:
  - name: http
    port: 80
