apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - name: http
      port: 80
      # targetPort: 80 # forward to port 80 inside k8s cluster
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  type: NodePort
  selector:
    app: activemq
  ports:
    - name: http
      port: 8161
      nodePort: 30010